vim.g.mapleader = " "
local builtin = require("telescope.builtin")
local hop = require("hop")
local directions = require("hop.hint").HintDirection

vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Open Telescope in find files mode" })
vim.keymap.set("n", "<leader>ee", ":Ntree<CR>", { desc = "Open Nerd tree" })
vim.keymap.set("n", "<leader>ng", ":Neogit kind=tab<CR>", { desc = "Open Neo git in split window" })
vim.keymap.set("n", "yrn", ":lua require('rest-nvim').run()<CR>", { desc = "Open Neo git in split window" })
vim.keymap.set("n", "<leader>tn", ":tabnew<CR>", { desc = "New tab" })
vim.keymap.set("n", "<S-Tab>", ":tabnext<CR>", { desc = "Go to next tab" })
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>", { desc = "Exit to terminal mode" })
vim.keymap.set("n", "<leader>tt", ":tabnew | terminal<CR>", { desc = "Open new terminal in new tab" })
vim.keymap.set("n", "f", function()
	hop.hint_char1({ direction = directions.AFTER_CURSOR })
end, { desc = "Go to find char after cursor", remap = true })
vim.keymap.set("n", "F", function()
	hop.hint_char1({ direction = directions.BEFORE_CURSOR })
end, { desc = "Go to find char before cursor", remap = true })
vim.keymap.set("n", "t", function()
	hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })
end, { desc = "Go to char in line after cursor", remap = true })
vim.keymap.set("n", "T", function()
	hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })
end, { desc = "Go to char in line before cursor", remap = true })
